11/02/21 (17:55:50) | ERROR: Data collection thread failed with exception: [Errno 6] Device not configured
Traceback (most recent call last):
  File "/Users/dhruvmanilawala/.pyenv/versions/3.9.1/lib/python3.9/site-packages/bpytop.py", line 2908, in _runner
    collector._collect()
  File "/Users/dhruvmanilawala/.pyenv/versions/3.9.1/lib/python3.9/site-packages/bpytop.py", line 3514, in _collect
    up_stat = psutil.net_if_stats()
  File "/Users/dhruvmanilawala/.pyenv/versions/3.9.1/lib/python3.9/site-packages/psutil/__init__.py", line 2216, in net_if_stats
    return _psplatform.net_if_stats()
  File "/Users/dhruvmanilawala/.pyenv/versions/3.9.1/lib/python3.9/site-packages/psutil/_psosx.py", line 266, in net_if_stats
    mtu = cext_posix.net_if_mtu(name)
OSError: [Errno 6] Device not configured
11/02/21 (17:55:52) | WARNING: Exiting with errorcode (1). Runtime 7:39:27 

11/02/21 (20:06:54) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/Users/dhruvmanilawala/.pyenv/versions/3.9.1/lib/python3.9/site-packages/bpytop.py", line 2908, in _runner
    collector._collect()
  File "/Users/dhruvmanilawala/.pyenv/versions/3.9.1/lib/python3.9/site-packages/bpytop.py", line 3518, in _collect
    cls._get_nics()
  File "/Users/dhruvmanilawala/.pyenv/versions/3.9.1/lib/python3.9/site-packages/bpytop.py", line 3482, in _get_nics
    up_stat = psutil.net_if_stats()
  File "/Users/dhruvmanilawala/.pyenv/versions/3.9.1/lib/python3.9/site-packages/psutil/__init__.py", line 2216, in net_if_stats
    return _psplatform.net_if_stats()
  File "/Users/dhruvmanilawala/.pyenv/versions/3.9.1/lib/python3.9/site-packages/psutil/_psosx.py", line 262, in net_if_stats
    names = net_io_counters().keys()
OSError: [Errno 12] Cannot allocate memory
11/02/21 (20:06:56) | WARNING: Exiting with errorcode (1). Runtime 2:09:32 

15/02/21 (06:22:44) | ERROR: Data collection thread failed with exception: [Errno 6] Device not configured
Traceback (most recent call last):
  File "/Users/dhruvmanilawala/.pyenv/versions/3.9.1/lib/python3.9/site-packages/bpytop.py", line 2908, in _runner
    collector._collect()
  File "/Users/dhruvmanilawala/.pyenv/versions/3.9.1/lib/python3.9/site-packages/bpytop.py", line 3514, in _collect
    up_stat = psutil.net_if_stats()
  File "/Users/dhruvmanilawala/.pyenv/versions/3.9.1/lib/python3.9/site-packages/psutil/__init__.py", line 2216, in net_if_stats
    return _psplatform.net_if_stats()
  File "/Users/dhruvmanilawala/.pyenv/versions/3.9.1/lib/python3.9/site-packages/psutil/_psosx.py", line 266, in net_if_stats
    mtu = cext_posix.net_if_mtu(name)
OSError: [Errno 6] Device not configured
15/02/21 (06:22:46) | WARNING: Exiting with errorcode (1). Runtime 7:59:13 

24/02/21 (12:58:17) | ERROR: Data collection thread failed with exception: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/Users/dhruvmanilawala/.local/pipx/venvs/bpytop/lib/python3.9/site-packages/bpytop.py", line 2924, in _runner
    collector._collect()
  File "/Users/dhruvmanilawala/.local/pipx/venvs/bpytop/lib/python3.9/site-packages/bpytop.py", line 3534, in _collect
    cls._get_nics()
  File "/Users/dhruvmanilawala/.local/pipx/venvs/bpytop/lib/python3.9/site-packages/bpytop.py", line 3498, in _get_nics
    up_stat = psutil.net_if_stats()
  File "/Users/dhruvmanilawala/.local/pipx/venvs/bpytop/lib/python3.9/site-packages/psutil/__init__.py", line 2216, in net_if_stats
    return _psplatform.net_if_stats()
  File "/Users/dhruvmanilawala/.local/pipx/venvs/bpytop/lib/python3.9/site-packages/psutil/_psosx.py", line 262, in net_if_stats
    names = net_io_counters().keys()
OSError: [Errno 12] Cannot allocate memory
24/02/21 (12:58:19) | WARNING: Exiting with errorcode (1). Runtime 1:21:35 

